# Generated by Django 5.0.6 on 2026-05-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteClonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comprobante_original', models.IntegerField(help_text='ID del comprobante original', unique=True)),
                ('id_cliente', models.IntegerField(help_text='ID del cliente en la tabla original')),
                ('id_sede', models.IntegerField()),
                ('turno', models.CharField(max_length=50)),
                ('referenciaticket', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=10)),
                ('correlativo', models.IntegerField()),
                ('tipocomprobante', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('enviosunat', models.IntegerField(default=0)),
                ('identificador', models.IntegerField()),
                ('usercreated', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_clonacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se clonó')),
                ('enviado_sunat', models.BooleanField(default=False, help_text='Indica si ya se envió a SUNAT')),
                ('respuesta_sunat', models.TextField(blank=True, help_text='Respuesta de SUNAT (XML/JSON)', null=True)),
                ('fecha_envio_sunat', models.DateTimeField(blank=True, help_text='Fecha de envío a SUNAT', null=True)),
            ],
            options={
                'verbose_name': 'Comprobante Clonado',
                'verbose_name_plural': 'Comprobantes Clonados',
                'db_table': 'comprobanteclonada',
            },
        ),
        migrations.CreateModel(
            name='SedeClonada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sede_original', models.IntegerField(help_text='ID de la sede original', unique=True)),
                ('nombre', models.CharField(max_length=500)),
                ('valor_igv', models.DecimalField(decimal_places=2, max_digits=18)),
                ('identificador', models.IntegerField()),
                ('serie_factura', models.CharField(max_length=50)),
                ('serie_boleta', models.CharField(max_length=50)),
                ('correlativo_boleta', models.IntegerField()),
                ('correlativo_factura', models.IntegerField()),
                ('serie_nota_credito_boleta', models.CharField(max_length=50)),
                ('correlativo_nota_credito_boleta', models.IntegerField()),
                ('serie_nota_credito_factura', models.CharField(max_length=50)),
                ('correlativo_nota_credito_factura', models.IntegerField()),
                ('ruta', models.TextField()),
                ('token', models.TextField()),
                ('serie_ticket', models.CharField(max_length=50)),
                ('correlativo_ticket', models.IntegerField()),
                ('nombre_impresora', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_created', models.CharField(max_length=50)),
                ('user_modified', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_clonacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se clonó')),
            ],
            options={
                'verbose_name': 'Sede Clonada',
                'verbose_name_plural': 'Sedes Clonadas',
                'db_table': 'sedeclonada',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDetClonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_detalle_original', models.IntegerField(help_text='ID del detalle original', unique=True)),
                ('id_producto', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('tipoventa', models.CharField(max_length=50)),
                ('codproductosunat', models.CharField(max_length=15)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_clonacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se clonó')),
                ('id_comprobante_clonado', models.ForeignKey(db_column='id_comprobante_clonado', help_text='Comprobante clonado al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, to='facturacion.comprobanteclonado')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante Clonado',
                'verbose_name_plural': 'Detalles de Comprobante Clonados',
                'db_table': 'comprobantedetclonada',
            },
        ),
    ]
